---
displayName: Function Template
description: Java contextual driven FaaS template
tags: ["Java", "OpenJDK", "Maven", "Debian", "Function"]
icon: /images/chime-function.svg
globalMemoryLimit: 2674Mi
