---
displayName: Java Application
description: RAN automation application template for Java
tags: ["Java", "OpenJDK", "Maven", "Debian", "Application"]
icon: /images/java.svg
globalMemoryLimit: 2674Mi
