---
displayName: RAN Application (rApp)
description: Java RAN automation application template
tags: ["Java", "OpenJDK", "Maven", "Debian", "Application"]
icon: /images/chime-app.svg
globalMemoryLimit: 2674Mi
