---
displayName: Java Application
description: An application contains an algorithm that receives input data, processes that data, producing results. Ensure that your work is algorithm-centered, encompassing input, algorithm, and output.
tags: ["Java", "OpenJDK", "Maven", "Debian", "Application"]
icon: /images/java.svg
globalMemoryLimit: 2674Mi
