---
displayName: NodeJS Express Application
description: AnRAN automation application template for Node
tags: ["NodeJS", "Express", "ubi8", "Application"]
icon: /images/nodejs.svg
globalMemoryLimit: 2198Mi
