# This is a basic workflow that is manually triggered

name: Manual Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - 7.21x

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Login to docker.io
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push base images
        run: /bin/bash arbitrary-users-patch/build_images.sh --push

      - name: Build and push devfile image
        run: |
          SHORT_SHA1=$(git rev-parse --short HEAD)
          docker build -t chime-devfile-registry -f ./build/dockerfiles/Dockerfile --target registry .
          docker tag chime-devfile-registry cellwizeplatform/chime-devfile-registry:7.21
          docker push cellwizeplatform/chime-devfile-registry:7.21
          docker tag chime-devfile-registry cellwizeplatform/chime-devfile-registry:${SHORT_SHA1}
          docker push cellwizeplatform/chime-devfile-registry:${SHORT_SHA1}
